import { Word } from '../types/index';

const WORDS_FIXED: Array<Word> = [
    {val: 'die Auftragslage', translation: 'ситуация с заказом', mark: 3},
    {val: 'locker', translation: 'легкий, непринужденний', mark: 3},
    {val: 'im Auge behalten', translation: 'держать на виду (наблюдать)', mark: 3},
  
    {val: 'die Direktheit', translation: 'прямота непосредственность', mark: 3},
    {val: 'effizient', translation: 'эффективный', mark: 3},
  {val: 'sich einarbeiten', translation: 'вработаться / освоится', mark: 3},
  {val: 'sich auf jemanden einlassen', translation: 'взять под шефство', mark: 3},
  {val: 'auf jemanden sich rechnen', translation: 'рассчитывать на кого-либо', mark: 3},
  {val: 'zum Punkt kommen', translation: 'перейти к сути', mark: 3},
  {val: 'jemanden übernehmen', translation: 'принять кого либо на работу', mark: 3},
  {val: 'die Annahme verweigern',translation: 'отказ от приемки товара', mark: 3},
  {val: 'die Artikulation', translation: 'артикуляция', mark: 3},
  {val: 'die Floskel', translation: 'пустая фраза', mark: 3},
  {val: 'der Klang', translation: 'звук / звучание', mark: 3},
  {val: 'mitfühlen', translation: 'сочувствовать / сострадать', mark: 3},
  {val: 'das Selbstvertrauen', translation: 'уверенность в себе', mark: 3},
  {val: 'termingerecht', translation: 'своевременно', mark: 3},
  {val: 'Boden Stromleitungen verlegen', translation: 'проложить электросеть по земле', mark: 3},
  {val: 'nähen', translation: 'шить', mark: 3},
  {val: 'die Dichtung', translation: 'прокладка / уплотнитель / поэзия / драматургия', mark: 3},
  {val: 'auswechseln', translation: 'заменить', mark: 3},
  {val: 'eine Steckdose anbringen', translation: 'установить розетку', mark: 3},
  {val: 'tapezieren', translation: 'обклеивать обоями', mark: 3},
  {val: 'der Schraubenzieher', translation: 'отвертка', mark: 3},
  {val: 'Metallstücke zusammenschweißen', translation: 'сваривать куски металла', mark: 3},
  {val: 'das Dach decken', translation: 'крыть крышу', mark: 3},
  {val: 'Waschbecken montieren', translation: 'устанавливать раковину', mark: 3},
  {val: 'die Nadel', translation: 'иголка / булавка / спица', mark: 3},
  {val: 'der Faden', translation: 'нить', mark: 3},
  {val: 'der Stoff', translation: 'материал / ткань / вещество', mark: 3},
  {val: 'das Maßband', translation: 'рулетка / мерная лента', mark: 3},
  {val: 'defekt', translation: 'дефект', mark: 3},
  {val: 'das Abflussrohr', translation: 'канализационная труба', mark: 3},
  {val: 'der Heimwerker', translation: 'домашний мастер / кустарь', mark: 1},
  {val: 'Hilfe benötigen', translation: 'нуждатся в помощи', mark: 3},
  {val: 'die Montageanleitung', translation: 'инструкция по сборке', mark: 3},
  {val: 'allein klarkommen', translation: 'справляться в одиночку', mark: 3},
  {val: 'den Haupthahn zudrehen', translation: 'выключить главный кран', mark: 3},
  {val: 'Wasser ablassen', translation: 'слить воду', mark: 3},
  {val: 'das Ventil', translation: 'вентиль / клапан', mark: 3},
  {val: 'ein Baby wickeln', translation: 'пеленать ребенка', mark: 1},
  {val: 'abdecken', translation: 'накривать / покривать /удовлетворять / гарантировать', mark: 1},
  {val: 'die Klappe', translation: 'клапан / откидная кришка /рот', mark: 1},
  {val: 'einen Fleck entfernen', translation: 'удалить пятно', mark: 1},
  {val: 'erneuern', translation: 'обновить', mark: 1},
  {val: 'zuschneiden', translation: 'вырезать по размеру', mark: 1},
  {val: 'für sich sprechen', translation: 'говорят сами за себя', mark: 1},
  {val: 'sich fest etablieren', translation: 'прочно утвердиться', mark: 1},
  {val: 'sich eintragen für', translation: 'зарегистрироваться', mark: 1},
  {val: 'etwas zur Verfügung stellen', translation: 'предоставлять что-то в распоряжение', mark: 1},
  {val: 'der Fortbildungsbedarf', translation: 'необходимость в дополнительном обучении', mark: 1},
  {val: 'die Grundlage legen', translation: 'заложить фундамент'},
  {val: 'ausgerechnet dann, wenn', translation: 'как раз когда'},
  {val: 'verbilligen', translation: 'удешевить'},
  {val: 'die Instandhaltung', translation: 'Обслуживание'},
  {val: 'die Wartung', translation: 'Техническое обслуживание'},
  {val: 'senken', translation: 'уменьшать'},
  {val: 'einen Vorschlag umsetzen', translation: 'Реализовать предложение (какое-то)'},
  {val: 'unterkommen', translation: 'устроится на рабрту / поселится'},
  {val: 'einen guten Ruf haben', translation: 'иметь хорошую репутацию'},
  {val: 'widersprechen', translation: 'противоречить'},
  {val: 'die Messung', translation: 'Измерение / Обьем'},
  {val: 'die Auswirkung', translation: 'влияние'},
  {val: 'sich Gedanken machen über', translation: 'размышлять о / переживать о'},
  {val: 'die Zuwanderung', translation: 'миграция / иммиграция'},
  {val: 'die Fahrzeit', translation: 'время в пути / длительность поездки'},
  {val: 'in Kauf nehmen', translation: 'принимать к сведению / соглашаться'},
  {val: 'jemandem Hilfe leisten', translation: 'помогать кому-то'},
  {val: 'ein Gespräch führen', translation: 'вести разговор'},
  {val: 'mithilfe von', translation: 'с помощью'},
  {val: 'überzeugt von', translation: 'убежден в'},
  {val: 'beiliegende Zeugnisse', translation: 'прилагаемые документы'},
  {val: 'beruflich / ehrenamtlich tätig sein', translation: 'заниматься профессиональной / волонтерской деятельностью'},
  {val: 'überdurchschnittlich', translation: 'выше среднего'},
  {val: 'unterdurchschnittlich', translation: 'ниже среднего'},
  {val: 'vernünftig', translation: 'разумний / понятний / нормальний'},
  {val: 'vielfältig', translation: 'разнообразный'},
  {val: 'die Laufzeit des Vertrages', translation: 'срок действия контракта'},
  {val: 'der Vertragsbeginn', translation: 'начало контракта'},
  {val: 'die Vergütung', translation: 'вознаграждение / компенсация'},
  {val: 'betragen', translation: 'составлять / быть (о сумме)'},
  {val: 'sich verpflichten zu', translation: 'обязаться что-то сделать'},
  {val: 'das Ausscheiden', translation: 'уход / выход из организации'},
  {val: 'wetterfest', translation: 'погодостойкий'},
  {val: 'altersmäßig', translation: 'по возрасту / возрастной'},
  {val: 'die Begrenzung', translation: 'ограничение'},
  {val: 'sich richten an', translation: 'обращаться к'},
  {val: 'die Überbrückung', translation: 'переход / преодоление'},
  {val: 'verfallen / wertlos', translation: 'протухший / бесценный'},
  {val: 'einheimisch', translation: 'местный / туземный'},
  {val: 'jeweiligen', translation: 'соответствующий'},
  {val: 'Erfordernisse', translation: 'требования'},
  {val: 'vorzeitig', translation: 'досрочно'},
  {val: 'den Schadenersatz verlangen', translation: 'потребовать компенсацию'},
  {val: 'wenn die andere Partei den Gründ für die Auflösung zu vertreten hat', translation: 'если причина расторжения договора лежит на другой стороне.'},
  ];

export default WORDS_FIXED;
